# Generated by Django 5.0.4 on 2024-04-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notesmodel",
            name="name",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
